OnlineBanking/Models/OnlineBankingContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
namespace Banka.Models
{
    public class OnlineBankingContext : DbContext
    {
        public DbSet<Racun> Racuni { get; set; }
        public DbSet<Uplatnica> Uplatnice { get; set; }

        public OnlineBankingContext()
        {

        }
    }
}

OnlineBanking/Models/Racun.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace Banka.Models
{
    public class Racun
    {
        public int RacunId { get; set; }

        [Required(ErrorMessage ="Obavezno polje")]
        public string NosilacRacuna { get; set; }

        [Required(ErrorMessage ="Obavezno polje")]
        [RegularExpression(@"\d{5}-\d{5}-\d{5}", ErrorMessage = "Broj mora biti u formatu xxxxx-xxxxx-xxxxx")]
        public string BrojRacuna { get; set; }
        
        public bool Aktivan { get; set; }
        public bool Online { get; set; }
        
     
    }

    
}

OnlineBanking/Models/Uplatnica.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace Banka.Models
{
    public class Uplatnica
    {
        public int UplatnicaId { get; set; }
        public int RacunId { get; set; }
        public Racun Racun { get; set; }

        [Required(ErrorMessage = "Obavezno polje")]
        public double IznosUplate { get; set; }

        [Required(ErrorMessage ="Obavezno polje")]
        [RegularExpression(@"\d{2}-\d{2}-\d{4}", ErrorMessage = "Datum mora biti u formatu dd-mm-yyyy")]
        public string DatumPrometa { get; set; }

        [Required(ErrorMessage ="Obavezno polje")]
        public string SvrhaUplate { get; set; }

        [Required(ErrorMessage ="Obavezno polje")]
        public string Uplatilac { get; set; }
        public bool Hitno { get; set; }

       
    }
}

OnlineBanking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineBanking.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

OnlineBanking/Controllers/RacunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Banka.Repository.Interfaces;
using Banka.Repository;
using Banka.Models;
namespace Banka.Controllers
{
    public class RacunController : Controller
    {
        // GET: Racun
        public IRacunRepo racunRepo = new RacunRepo();
        public IUplatnicaRepo uplatnicaRepo = new UplatnicaRepo();
        public ActionResult Index()
        {
            var racuni = racunRepo.GetAll();
            ViewBag.Racuni = racuni;
            return View();
        }

        [HttpPost]
        public ActionResult Index([Bind(Include = "RacunId, NosilacRacuna, BrojRacuna, Aktivan, Online")]Racun racun)
        {
          
            var racuni = racunRepo.GetAll();
            ViewBag.Racuni = racuni;

            if (ModelState.IsValid)
            {
                racunRepo.Create(racun);
                return RedirectToAction("Index");
            }


            return View(racun);
            
        }

        public ActionResult Edit(int id)
        {
            var racun = racunRepo.GetById(id);
            ViewBag.NosilacRacuna = racun.NosilacRacuna;
            ViewBag.BrojRacuna = racun.BrojRacuna;
            return View(racun);
        }

        [HttpPost]
        public ActionResult Edit(Racun racun)
        {
            if (ModelState.IsValid)
            {
                racunRepo.Edit(racun);
                return RedirectToAction("Index");
            }
            return View(racun);
        }

        public ActionResult Delete(int id)
        {
            racunRepo.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult ChangeStatus(int id)
        {
            var racun = racunRepo.GetById(id);
            racunRepo.ChangeStatus(racun);
            return RedirectToAction("Index");
        }

    }
}

OnlineBanking/Controllers/UplatnicaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Banka.Repository.Interfaces;
using Banka.Repository;
using Banka.Models;
namespace Banka.Controllers
{
    public class UplatnicaController : Controller
    {
        // GET: Uplatnica
        IUplatnicaRepo uplatnicaRepo = new UplatnicaRepo();
        IRacunRepo racunRepo = new RacunRepo();
        public ActionResult Index(int id)
        {
            double suma = 0;
            var racun = racunRepo.GetById(id);
            ViewBag.BrojRacuna = racun.BrojRacuna;
            ViewBag.NosilacRacuna = racun.NosilacRacuna;
            ViewBag.RacunId = racun.RacunId;
            ViewBag.StatusRacuna = racun.Aktivan.ToString();
            var upl = uplatnicaRepo.GetAll(id);
            foreach (var up in upl)
            {
                suma += up.IznosUplate;
            }
            ViewBag.Uplatnice = upl;
            ViewBag.Suma = suma;
            return View();
        }

        [HttpPost]
        public ActionResult Index(Uplatnica uplatnica, int id)
        {
            double suma = 0;
            var racun = racunRepo.GetById(id);
            ViewBag.BrojRacuna = racun.BrojRacuna;
            ViewBag.NosilacRacuna = racun.NosilacRacuna;
            ViewBag.RacunId = racun.RacunId;
            ViewBag.StatusRacuna = racun.Aktivan.ToString();
            var upl = uplatnicaRepo.GetAll(id);
            foreach (var up in upl)
            {
                suma += up.IznosUplate;
            }
            ViewBag.Uplatnice = upl;
            ViewBag.Suma = suma;
            if (ModelState.IsValid)
            {
                uplatnicaRepo.Create(uplatnica, id);

                return RedirectToAction("Index", new { id = uplatnica.RacunId });
            }

            return View(uplatnica);
        }

        public ActionResult Edit(int id)
        {
           
            var uplatnica = uplatnicaRepo.GetById(id);
            var racun = racunRepo.GetById(uplatnica.RacunId);
            var racuni = racunRepo.GetAll();
            ViewBag.BrojRacuna = racun.BrojRacuna;
            ViewBag.NosilacRacuna = racun.NosilacRacuna;
            ViewBag.Racuni = new SelectList(racuni, "RacunId", "BrojRacuna");
            return View(uplatnica);
            
        }

        [HttpPost]
        public ActionResult Edit(Uplatnica uplatnica)
        {
            var racuni = racunRepo.GetAll();
            var racun = racunRepo.GetById(uplatnica.RacunId);
            ViewBag.Racuni = new SelectList(racuni, "RacunId", "BrojRacuna", uplatnica.RacunId);
            ViewBag.BrojRacuna = racun.BrojRacuna;
            ViewBag.NosilacRacuna = racun.NosilacRacuna;
            if (ModelState.IsValid)
            {
                uplatnicaRepo.Edit(uplatnica);
                return RedirectToAction("Index", new { id = uplatnica.RacunId });
            }
          
          
            return View(uplatnica);
        }

        public ActionResult Delete(int id)
        {
            var uplatnica = uplatnicaRepo.GetById(id);
            var racun = racunRepo.GetById(uplatnica.RacunId);
            uplatnicaRepo.Delete(id);
            return RedirectToAction("Index", new { id = racun.RacunId });
        }

    

    }
}

OnlineBanking/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OnlineBanking/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineBanking/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

OnlineBanking/Views/Racun/Edit.cshtml
@model Banka.Models.Racun

@{
    ViewBag.Title = "Edit";
}

<h2>Izmena računa za: @ViewBag.NosilacRacuna</h2>

<h4>Broj računa: @ViewBag.BrojRacuna</h4>

@using (Html.BeginForm("Edit", "Racun", FormMethod.Post))
{

    <table>

        @Html.HiddenFor(model=>model.RacunId)
        <tr>
            <td> @Html.LabelFor(model => model.NosilacRacuna) </td>

            <td>@Html.TextBoxFor(model => model.NosilacRacuna)</td>
            <td> @Html.ValidationMessageFor(model => model.NosilacRacuna, "", new { @class = "text-danger" })</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.BrojRacuna)</td>

            <td>@Html.TextBoxFor(model => model.BrojRacuna)</td>
            <td>@Html.ValidationMessageFor(model => model.BrojRacuna, "", new { @class = "text-danger" })</td>

        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Aktivan)</td>
            <td>@Html.CheckBoxFor(model => model.Aktivan)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Online)</td>

            <td> @Html.CheckBoxFor(model => model.Online)</td>
        </tr>


        <tr>
            <td><input type="submit" value="Sačuvaj izmene" /></td>
        </tr>
    </table>
}

OnlineBanking/Views/Racun/Index.cshtml
@model Banka.Models.Racun

@{
    ViewBag.Title = "Index";
}

<h2>Lista računa</h2>

<table class="table table-bordered">
    <tr>
        <td><b>Broj racuna</b></td>
        <td><b>Nosilac racuna</b></td>
        <td><b>Aktivan</b></td>
        <td><b>Online</b></td>

    </tr>

    @foreach (var item in ViewBag.Racuni as IEnumerable<Banka.Models.Racun>)
    {

        if (item.Aktivan)
        {
            <tr style="background:lightgreen">
                <td>@item.BrojRacuna</td>
                <td>@item.NosilacRacuna</td>
                <td><span>Da</span></td>
                <td>
                    @if (@item.Online)
                {
                    <span>Da</span>
                }
                else
                {
                    <span>Ne</span>
                }
            </td>
            
            <td>@Html.ActionLink("Otvori", "Index", new { controller = "Uplatnica", id = item.RacunId })</td>
            <td>@Html.ActionLink("Izmeni", "Edit", new { id = item.RacunId })</td>
            <td>@Html.ActionLink("Obrisi", "Delete", new { id = item.RacunId })</td>
            <td>@Html.ActionLink("Deaktiviraj", "ChangeStatus", new { id = item.RacunId })</td>
        </tr>
        }
        else
        {
            <tr style="background:red">
                <td>@item.BrojRacuna</td>
                <td>@item.NosilacRacuna</td>
                <td><span>Ne</span></td>
                <td>
                    @if (@item.Online)
                    {
                        <span>Da</span>
                    }
                    else
                    {
                        <span>Ne</span>
                    }
                </td>           
                <td>@Html.ActionLink("Otvori", "Index", new { controller = "Uplatnica", id = item.RacunId })</td>
                <td>@Html.ActionLink("Izmeni", "Edit", new { id = item.RacunId })</td>
                <td>@Html.ActionLink("Obrisi", "Delete", new { id = item.RacunId })</td>
                <td>@Html.ActionLink("Aktiviraj", "ChangeStatus", new { id = item.RacunId })</td>
            </tr>
        }
    }
</table>
<hr />

<h2>Dodaj novi račun</h2>

@using (Html.BeginForm("Index", "Racun", FormMethod.Post))
{

    <table>

        <tr>
            <td> @Html.LabelFor(model => model.NosilacRacuna) </td>

            <td>@Html.TextBoxFor(model => model.NosilacRacuna)</td>
            <td> @Html.ValidationMessageFor(model => model.NosilacRacuna, "", new { @class = "text-danger"})</td>
        </tr>

        <tr>
            <td>@Html.LabelFor(model => model.BrojRacuna)</td>

            <td>@Html.TextBoxFor(model => model.BrojRacuna)</td>
            <td>@Html.ValidationMessageFor(model => model.BrojRacuna, "",new { @class = "text-danger" })</td>

        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Aktivan)</td>
            <td>@Html.CheckBoxFor(model => model.Aktivan)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Online)</td>

            <td> @Html.CheckBoxFor(model => model.Online)</td>
        </tr>


        <tr>
            <td><input type="submit"  value="Dodaj novi račun" /></td>
        </tr>
    </table>
}

OnlineBanking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("OnlineBanking", "Index", "Racun", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
              
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - By Nemanja Medan</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

OnlineBanking/Views/Uplatnica/Edit.cshtml
@model Banka.Models.Uplatnica
@{
    ViewBag.Title = "Edit";
}

<h2>Izmeni uplatnicu za račun: @ViewBag.BrojRacuna</h2>

<h4>Nosilac računa: @ViewBag.NosilacRacuna</h4>

@using (Html.BeginForm("Edit", "Uplatnica", FormMethod.Post))
{

    @Html.HiddenFor(model=>model.UplatnicaId)
    <table>
        <tr>
            <td> @Html.LabelFor(model => model.IznosUplate)</td>

            <td> @Html.TextBoxFor(model => model.IznosUplate) </td>
            <td>@Html.ValidationMessageFor(model => model.IznosUplate, "", new { @class = "text-danger" })</td>

        </tr>
        <tr>
            <td> @Html.LabelFor(model => model.DatumPrometa)</td>

            <td>  @Html.TextBoxFor(model => model.DatumPrometa) </td>
            <td>  @Html.ValidationMessageFor(model => model.DatumPrometa, "", new { @class = "text-danger" })</td>

        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.SvrhaUplate)</td>

            <td> @Html.TextBoxFor(model => model.SvrhaUplate)</td>
            <td>  @Html.ValidationMessageFor(model => model.SvrhaUplate, "", new { @class = "text-danger" })</td>

        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Uplatilac)</td>
            <td>
                @Html.TextBoxFor(model => model.Uplatilac)
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.Uplatilac, "", new { @class = "text-danger" })
            </td>

        </tr>
        <tr>
            <td>
                @Html.LabelFor(model => model.Racun)
            </td>
            <td>
                @Html.DropDownListFor(model => model.RacunId, ViewBag.Racuni as SelectList)
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Hitno)</td>

            <td>@Html.CheckBoxFor(model => model.Hitno)</td>

        </tr>


        <tr><td><input type="submit" value="Sačuvaj izmene" /></td></tr>
    </table>
}

OnlineBanking/Views/Uplatnica/Index.cshtml
@model Banka.Models.Uplatnica

@{
    ViewBag.Title = "Index";
}


<h2>Rad sa računom: @ViewBag.BrojRacuna</h2>

<h4>Vlasnik računa: @ViewBag.NosilacRacuna</h4>

<h4>Spisak svih transakcija:</h4>
<table class="table table-bordered">
    <tr>
        <td><b>Uplatilac</b></td>
        <td><b>Iznos uplate</b></td>d
        <td><b>Datum promenta</b></td>
        <td><b>Svrha uplate</b></td>
        <td><b>Hitno</b></td>
    </tr>
    
    @foreach (var item in ViewBag.Uplatnice as IEnumerable<Banka.Models.Uplatnica>)
    {

        if (item.IznosUplate >= 0)
        {
            <tr style="background:lightgreen">
                <td>@item.Uplatilac</td>
                <td>@item.IznosUplate</td>
                <td>@item.DatumPrometa</td>
                <td>@item.SvrhaUplate</td>
                <td>
                    @if (@item.Hitno)
                    {
                        <span>Da</span>
                    }
                    else
                    {
                        <span>Ne</span>
                    }
                </td>

                <td>@Html.ActionLink("Izmeni", "Edit", new { id = item.UplatnicaId })</td>
                <td>@Html.ActionLink("Obrisi", "Delete", new { id = item.UplatnicaId })</td>

            </tr>
        }
        else
        {
            <tr style="background:red">
                <td>@item.Uplatilac</td>
                <td>@item.IznosUplate</td>
                <td>@item.DatumPrometa</td>
                <td>@item.SvrhaUplate</td>
                <td>
                    @if (@item.Hitno)
                    {
                        <span>Da</span>
                    }
                    else
                    {
                        <span>Ne</span>
                    }
                </td>
              

                <td>@Html.ActionLink("Izmeni", "Edit", new { id = item.UplatnicaId})</td>
                <td>@Html.ActionLink("Obrisi", "Delete", new { id = item.UplatnicaId})</td>

            </tr>
        }
    }
</table>

<h4>Ukupno: @ViewBag.Suma</h4>
<hr />
@if (ViewBag.StatusRacuna == "True") {
<h2>Izvrši novu transakciju</h2>
using (Html.BeginForm("Index", "Uplatnica", FormMethod.Post, new { id = ViewBag.RacunId }))
{


    <table>
        <tr>
            <td> @Html.LabelFor(model => model.IznosUplate)</td>
          
            <td> @Html.TextBoxFor(model => model.IznosUplate) </td>  
            <td>@Html.ValidationMessageFor(model => model.IznosUplate, "", new { @class = "text-danger" })</td>
        
        </tr>
        <tr>
           <td> @Html.LabelFor(model => model.DatumPrometa)</td>
            
              <td>  @Html.TextBoxFor(model => model.DatumPrometa) </td>
            <td>  @Html.ValidationMessageFor(model => model.DatumPrometa, "", new { @class = "text-danger" })</td>
          
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.SvrhaUplate)</td>
            
            <td> @Html.TextBoxFor(model => model.SvrhaUplate)</td>
            <td>  @Html.ValidationMessageFor(model => model.SvrhaUplate, "", new { @class = "text-danger" })</td> 
          
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Uplatilac)</td>
            <td>
                @Html.TextBoxFor(model => model.Uplatilac)
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.Uplatilac, "", new { @class = "text-danger" })
            </td>
            
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Hitno)</td>
            
              <td>@Html.CheckBoxFor(model => model.Hitno)</td>
            
        </tr>


        <tr><td><input type="submit" class="btn-block" value="Dodaj novu transakciju" /></td></tr>
    </table>
}
}
else
{
    <h4 class="text-danger">Račun deaktiviran, vršenje transakcija nije moguće!</h4>
}
<hr />
@Html.ActionLink("Povratak na glavnu stranicu", "Index", "Racun")